version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=devpass
    volumes:
      - ./dashboard:/code/dashboard/
    working_dir:
      /code/dashboard/
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db